\documentclass{beamer}
\usepackage{apacite,geometry,fancyhdr,graphicx}

\title{Analysis of Massachusetts' Standardized Testing Multi-Group Structural Equation Modelling}
\author[shortname]{Landon Hurley \inst{1} \and Herb Susmann \inst{2}}
\institute[shortinst]{\inst{1} Psychology, SUNY Geneseo \and %
\inst{2} Mathematics, SUNY Geneseo}
\begin{document}



<<setup, include=FALSE, cache=FALSE, echo=FALSE, results='hide'>>=
library(lavaan)
library(psych)
library(mvpart)
library(semTools)

load("comp.RData")

Sys.setenv(TEXINPUTS=getwd(), 
           BIBINPUTS=getwd(), 
           BSTINPUTS=getwd())
@

\begin{frame}
  \titlepage
\end{frame}

\begin{frame}{Outline}
  \tableofcontents
\end{frame}

\begin{frame}{Introduction}
  \begin{itemize}
    \item Massachusetts standardized test data \pause
    \item Is the test psychometrically valid? \pause
    \item \textbf{No! It doesn't measure the same thing in the same way across groups.}
  \end{itemize}
\end{frame}

\section{Data}

  \begin{frame}{Data}
    \begin{itemize}
      \item 10,515 10th grade student test results \pause
      \item English, Math, and Science components \pause
      \item Answers from every question for each section \pause
      \item Basic demographic information from questionnaire \pause
    \end{itemize}
  \end{frame}

\section{Measurement Invariance}
  
  \begin{frame}{Measurement Invariance}
     \begin{itemize}
      \item{Testing:} set of standardized questions designed to elicit responses for use in measuring the traits, capacities, or achievements of an individual.
       \item{} Tests imply a global solution: the individual should never affect how items on the test perform.
        \item{} In psychometrics, validity is tested in one of two way: predictive invariance \& measurement (factorial) invariance.
      \end{itemize}
  \end{frame}
  \begin{frame}{Measurement Invariance Process}
    \begin{enumerate}
      \item{Configural invariance:} Tests whether the same factor model is found within each subgroup.
      \item{Weak invariance:} Tests whether in addition to the same factor structure, the same items load equivalently onto the same structure.
      \item{Strong invariance:} Tests that the intercepts, item loadings, and factor structure are equivalent across groups.
      \item{Strict invariance:} Tests the assumption that in addition to the preceding steps, the residual variances are equivalent across groups.
    \end{enumerate}
  \end{frame}
  \begin{frame}{Asessing model fit}
    \begin{itemize}
      \item{$\chi^2$}\begin{equation} \chi^2_{d.f.}=2(N-1) \cdot F_0 \end{equation}
      Scales with $N$, making it difficult to fit
      \item{CFI:} \begin{equation} 1-\frac{\chi^2_{t}-{df_t}}{\chi^2_{n}-{df_n}} \end{equation}
      \item{NNFI:} \begin{equation} 1-\frac{\frac{\chi^2_{t}}{df_t}}{\frac{\chi^2_{n}}{{df_n}}} \end{equation}
      \item{RMSEA:} \begin{equation} \sqrt{\frac{\chi^2_{df}-{df_t}}{df_t(N-1)}} \end{equation}
    \end{itemize}
  \end{frame}
  
\subsection{Results}

    \begin{frame}{Results}
      \begin{center}
        \includegraphics[keepaspectratio=true,width=2.7in]{english}
      \end{center}
    \end{frame}
    
    \begin{frame}{Results}
      \includegraphics[keepaspectratio=true,width=4.3in]{mathematics}
    \end{frame}
    
    \begin{frame}{Results}
      \includegraphics[keepaspectratio=true,width=4.3in]{biology}
    \end{frame}

    \begin{frame}{Results}
\vspace{0.25cm}
\begin{tabular}{|c|c|c|c|c|}
\hline 
English & $\chi^2$ & CFI & TLI & RMSEA
\tabularnewline
\hline 
\hline 
Comparison & -1670.297 & 0.030 & 0.034 & -0.006  \tabularnewline
\hline 
Strict fit indices & 6007.770 & 0.918 & 0.912 & 0.030 \tabularnewline
\hline 
\end{tabular}
\end{frame}
\begin{frame}{Results}
\vspace{0.25cm}
\begin{tabular}{|c|c|c|c|c|}
\hline 
Mathematics & $\chi^2$ & CFI & TLI & RMSEA
 \tabularnewline
\hline 
\hline 
Comparison & -998.348 & .014 & .017 & .005  \tabularnewline
\hline 
Strict fit indices & 4130.561 & .949 & .946 & .033 \tabularnewline
\hline 
\end{tabular}
\end{frame}
\begin{frame}{Results}
\vspace{0.25cm}
\begin{tabular}{|c|c|c|c|c|}
\hline 
Biology & $\chi^2$ & CFI & TLI & RMSEA
 \tabularnewline
\hline 
\hline 
Comparison & -2132.914 & .026 & .03 & .006  \tabularnewline
\hline 
Strict fit indices & 7686.782 & .926 & .922 & .031 \tabularnewline
\hline 
\end{tabular}
\end{frame}
  \subsection{Discussion}
    \begin{frame}{Discussion}
  Strict invariance: what does it mean for these tests?
      \begin{itemize}
      \item{SES:}
      Lack of strict invariance typically indicates that an unmeasured latent variable is differentially affecting the test outcome. In other words, the existence of unmeasured effects is specified by the existence of error variance heterogeneity. This is despite the invariance of both the factor model, the intercepts, and slopes.
      \item{Meredith (1993):}
      When using measures to make decisions “strict factorial invariance is essential.”
      \end{itemize}
    
    \end{frame}
    
\section{Regression Tree}
  \begin{frame}{Regression Tree}
  \begin{itemize}
  \item{} CART allows for complex relationships to be modelled within data without parametric assumptions or linearity.
  \item{} Multivariate regression trees are ideal in this instance because it can model both the complex relationships, but also non-response, in relation to a multiple vectored response surface: English, Mathematics, \& Science.
  \end{itemize}
  \end{frame}
  \begin{frame}{Results}
      <<echo=F,fig=T,fig.height=5.5,cache=T>>=
      mvpart(cbind(mrawsc,erawsc,srawsc)~.,data=d4)
      @
  \end{frame}
  \subsection{Discussion}
    \begin{frame}{Discussion}
    \begin{itemize}
      \item{Missing data:} Question 3 deals with after college goals. These results indicate that students who either intend to go to attain a baccalaureate degree OR skip the question perform better on the three sub-tests.
      \item{Ethncity:} Amongst students who do plan on a baccalaureate degree, ethnicity efficiently segments the science scores.
      \item{Quest14:} How often do you use scientific instruments?
      \item{Confirmation:} Each of the responses were regressed onto multiply imputed forms of the questionnaire, which had equivalent $R^2$, indicating effects were linear only.
      \end{itemize}
    \end{frame}
    
\section{Conclusions}
  \begin{frame}{Conclusions}
    \begin{itemize}
      \item Fails strict invariance \pause
      \item Regression tree: split on ethnicity
    \end{itemize}
  \end{frame}

\begin{frame}[allowframebreaks]
\frametitle{References}
\nocite{*}
\bibliography{references}{}
\bibliographystyle{apacite}
\end{frame}

\begin{frame}
  \frametitle{Appendix A}
  <<fig=T, echo=FALSE, fig.height=4, fig.width=5>>=
fa.diagram(feng,main='English Oblimin')
@
\end{frame}

\begin{frame}
  \frametitle{Appendix A}
  <<fig=T, echo=FALSE, fig.height=4, fig.width=5>>=
fa.diagram(fmat,main='Mathematics Oblimin')
@
\end{frame}

\begin{frame}
  \frametitle{Appendix A}
  <<fig=T, echo=FALSE, fig.height=4, fig.width=5>>=
fa.diagram(fsci1,main='Biology Oblimin')
@
\end{frame}

\end{document}
